### ISSUE TITLE
Using passive location for speeding up the process

### ISSUE THREAD

**Issue by david-serrano** [mumayank/AirLocation#1]
Hi @mumayank just been looking through your library and noticed it seems to be missing fetching passive locations available on the device which would avoid having to wake up receivers and the GPS/wifi location in several cases!! I've written a similar piece of code (without the permission handling bit) which is also available on github (https://github.com/david-serrano/locationprovider) in case you're interested. Also happy to receive feedback! :D

**Comment by mumayank** [comment]
Hey @david-serrano thank you for the feedback! I will look into this, kindly allow me some time :)

**Comment by KelvinPac** [comment]
Hi, I got an issue with this library where if the location is turned off and the google dialogue shows up to enable location after the user accepts to enable location nothing happens from there. the library seems to not listen for that event and try getting location again. So for the first time if the location is turned off it doesn't work. But for subsequent times when the location is on everything works fine. I didn't have time to go through the library code so I thought you could provide quick advice about this. Cheers for the awesome library.

**Comment by mumayank** [comment]
@david-serrano The lib has been upgraded to use passive locations. Additionally, v2 of this lib brings you live location updates! Hope you love using this lib. Thank you for your continuous support.

**Comment by KelvinPac** [comment]
Can't wait to try this out
