### ISSUE TITLE
can I update user location ?

### ISSUE THREAD

**Issue by kmIndonesia** [mumayank/AirLocation#11]
first of all, I want say thank you very much for this great library. the easiest implementation yet I can get the most accurate location. so awesome.

I want to get the latest user location whenever user open the app. the user maybe close the app for a while and open it again.

so I need to put getcoordinate code in onResume. can I do that using AirLocation ?

something like this

```
 override fun onResume() {
        super.onResume()
        
        airLocation.updateLocation()
    }
```
then get the updated location result onSuccess callback maybe

how to do that ? or can I do trick to achieve that ?

**Comment by mumayank** [comment]
Hey, thank you for the kind words.

Regarding your question, the answer is in the documentation:

Everytime you want to fetch user's current location, simply initialize airLocation variable :) The library takes care of the rest
