### ISSUE TITLE
can we stop to update location ?

### ISSUE THREAD

**Issue by kmIndonesia** [mumayank/AirLocation#18]
after updating location using `airLocation.start()`, can we manually stop to update the location ?
I mean something like `airLocation.stop()`, currently I am using version 2.4  and it seems there is no method to stop the update. is there any alternative way to do that ?

**Comment by irfnyas** [comment]
actually I've asked about this at https://github.com/mumayank/AirLocation/issues/16. check it out, hope it helps

**Comment by mumayank** [comment]
@ifnyas Thanks, @kmIndonesia Yes, please look into #16 for more on this.
