### ISSUE TITLE
Location not working in Android 10

### ISSUE THREAD

**Issue by abkoradiya** [mumayank/AirLocation#19]
Steps to reproduce the issue in the sample app.

--> Disable location
--> start app and grant permission for the location.
--> Press "No Thanks" button in GPS popup.
--> Then again start updates. This time press "Ok" in GPS Popup.
--> Now location not working. and always show **HIGH_PRECISION_LOCATION_NA_TRY_AGAIN_PREFERABLY_WITH_NETWORK_CONNECTIVITY** as an error.

**Comment by mumayank** [comment]
Thanks for bringing this up. This issue marks an example for all on how to correctly raise an issue. Really, thanks.

Coming to the issue, let me create an emulator with Android 10 and reproduce the error. I will get back on this on priority.

**Comment by AgungLaksana** [comment]
@mumayank your library is awesome. Hopefully this issue can be solved in the next update. Thank you very much

**Comment by abkoradiya** [comment]
> @mumayank your library is awesome. Hopefully this issue can be solved in the next update. Thank you very much

@mumayank Are you facing this issue?

**Comment by AgungLaksana** [comment]
@abkoradiya I had an error before but after I checked it, the error was nothing to do with AirLocation , AirLocation works without issue in my Redmi Note 7, Android 10.

**Comment by AgungLaksana** [comment]
@abkoradiya  btw, Initially my app was built using targetSdkVersion 28 (Android P), then I update my Android from Android P to Android 10, I update my targetSdkVersion to 29 in my gradle. run the app and then there are some weird behaviours in my app, not just AirLocation, even some EditText became weird. then I clear all cache, then my app works without any issue.

**Comment by Shubham178046** [comment]
if i allow location Permission and turn off gps and start Activity than show gps enable dialog box if I click ok than it will give me TextView null pointer exception bcz on that time onSuccess Method execute on Background and textview value not set in background

**Comment by mumayank** [comment]
Update: working on real device (Android 11/ Google Pixel 4a)
