### ISSUE TITLE
Air Location is Crashing

### ISSUE THREAD

**Issue by judeosbert** [mumayank/AirLocation#2]
Even after giving the flag for requesting permission, the Library is crashing since the permission is not requested.
I am using it in a java project and have only taken the kotlin classes, not as a dependency

**Comment by mumayank** [comment]
Hi, thanks for using the library. Unfortunately just copying classes won't be enough. You need to copy changes from Manifest file and app's build.gradle file as well. And since you're not using this library as stated in the readme doc, this is not an issue, I'm closing this.
I'd highly suggest you to imoort this lib via gradle.

**Comment by judeosbert** [comment]
Hi, Thanks for replying, I moved around the code to check and request the permission first and then fetch the location. This is working now. Thanks 
I didnt use the import options since it was giving me error during build. The play-services mentioned in the documentation was giving me error for the FCM message received function.

**Comment by mumayank** [comment]
@judeosbert
Could you please pass me the error that you were getting when trying to import this lib via gradle? I want to look into it. (If you could paste the entire error log along with your project level and app level gradle.build file snippets)

**Comment by judeosbert** [comment]
I dont think the error is related to your library, its more of different versions of dependency. 

    implementation 'com.google.firebase:firebase-messaging:11.6.0'
(this is our current implementation and gives no error [w/o] library]

was giving me
` error: cannot access zzbej
        Log.d(TAG, "New push message from: " + remoteMessage.getFrom());`


Upgraded it to 17.3.4 and the error is resolved.  This was the error preventing me from using airlocation as dependency, I guess i will add it as dependency since it resolved now.
