### ISSUE TITLE
Location permission not working in android 12 Samsung device.

### ISSUE THREAD

**Issue by aanalzb** [mumayank/AirLocation#26]
Hello,

I am using android 12 version and while getting location permission i got below error in on failure method.

HIGH_PRECISION_LOCATION_NA_TRY_AGAIN_PREFERABLY_WITH_NETWORK_CONNECTIVITY

**Comment by mumayank** [comment]
Unfortunately, this means that high-precision location could not be fetched. You may prompt the user to try again by connecting to some network first.
