### ISSUE TITLE
getting crash

### ISSUE THREAD

**Issue by manishbutola** [mumayank/AirLocation#3]
I am getting below error when i am using this library with my project

Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission

**Comment by mumayank** [comment]
As already [replied to your comment](https://medium.com/@mumayank/hi-if-you-follow-all-the-steps-as-mentioned-in-the-setup-section-it-should-really-work-fine-4672bfb56e14) on my [medium post of this library,](https://proandroiddev.com/airlocation-library-to-fetch-users-most-precise-location-via-a-callback-23135014282f) please note that these permissions are included in this [library's manifest file](https://github.com/mumayank/AirLocation/blob/master/airlocationlibrary/src/main/AndroidManifest.xml), and if you really follow all the steps mentioned in the [readme](https://github.com/mumayank/AirLocation), you'll not face any problem. Closing this issue.
