### ISSUE TITLE
Location not being received if location is initially turned off

### ISSUE THREAD

**Issue by KelvinPac** [mumayank/AirLocation#4]
Hi, I got an issue with this library where if the location is turned off and the google dialogue shows up to enable location after the user accepts to enable location nothing happens from there. the library seems to not listen for that event and try getting location again. So for the first time if the location is turned off it doesn't work. But for subsequent times when the location is on everything works fine. I didn't have time to go through the library code so I thought you could provide quick advice about this. Cheers for the awesome library.

**Comment by KelvinPac** [comment]
After some manual debugging I found that all events are sent to the activity. Apparently, I had left out `airLocation.onActivityResult(requestCode, resultCode, data);` which receives all events. 
I suggest in the sample ReadMe code you show or comment that to receive any events you have to add that. it's not optional

**Comment by mumayank** [comment]
@KelvinPac thank you for using the library! May you please help me understand why did you feel adding `airLocation.onActivityResult` was optional?
