### ISSUE TITLE
airLocation dose not update on location changed

### ISSUE THREAD

**Issue by saeedrnjbr** [mumayank/AirLocation#6]
how can i update airlocation on location change ? it dosent update ui when i change my place . updating ui , i must   close  and open  app again  , i have to do it over and over  .

**Comment by mumayank** [comment]
The library was built with the aim of giving the developer a quick way to get the app user's current most precise location (one time only). Live location updates is a feature request, which I will take up soon. Thank you for the feedback.

**Comment by saeedrnjbr** [comment]
i don't need to live Location  . i used library on my MainActivity, when i open application , it  finds   my current location perfect . when i close and open it in another place . it  unables  to fetch my new   location  , i think library  cached  my last location.

**Comment by saeedrnjbr** [comment]
i feel , we dont have same definition on LiveLocation  . i  closed app once , and every things has been reset . Naturally ,   airLocation must gets new location again,

**Comment by saeedrnjbr** [comment]
dose it cache last location or no ?

**Comment by mumayank** [comment]
The library does not cache the location. Every fetch is new and lasts one time only. You may cross verify by using any other location dependant app (best example: Google maps). Once you fetch the location from the AirLocation library, and if you feel the location is not new, but a cached version has been delivered to you, open Google maps and see your current location coordinates. If the coordinates are same as delivered by the AirLocation library, this proves that the GPS installed on your phone, or Google's location library (on which AirLocation and Google maps depend) are behind this issue.

**Comment by mumayank** [comment]
Since you said you are interested in one time precise location only, hence regularly updated location enhancement is not being requested for now. So, I'm closing this issue.
