### ISSUE TITLE
Get distance location

### ISSUE THREAD

**Issue by rhosy** [mumayank/AirLocation#8]
Can I get distance between two location or more using this library?

**Comment by mumayank** [comment]
Google maps library already has a very easy utility function to do this.
1. Head to https://developers.google.com/maps/documentation/android-sdk/utility/
2. Go to the last heading "Calculate distances, areas and headings via spherical geometry"
3. See the first point "computeDistanceBetween() – Returns the distance, in meters, between two latitude/longitude coordinates"
